### ISSUE TITLE
Before & After Feature methods are not executed when parallel element is set as "scenario"

### ISSUE THREAD

**Issue by anuragh27crony** [tokunbo/behave-parallel#10]
First of all thanks for this awesome functionality.

I have been trying to tweak Allure reporting framework for which i'm heavily depending on environment methods which behave provides.

One thing i noticed was when you run parallel-element as "scenario" it doesn't execute before & after feature methods. Just wanted to understand if this is a designed in that manner or possibly an issue.

Lemme know if u need any log.

**Comment by tokunbo** [comment]
o.o.... if you could provide some kind of simple example setup, it'd be awesome.

**Comment by tokunbo** [comment]
Actually, I see what you mean... the before_feature & after_feature inside feature/environment.py doesn't run. :-( ....if I can figure it out I'll fix it in the upstreamsync branch. Thanks for telling me about it.

**Comment by anuragh27crony** [comment]
Sure @tokunbo , Thanks alot. I would be happy to help with testing efforts incase if u come across any fix.

For others relying on before_feature & after_feature they can still use "**_feature_**" as parallel-element as workaround.

**Comment by tokunbo** [comment]
Okay, I think I've got it... try it out -^_^- 
https://github.com/tokunbo/behave-parallel/commit/4a2e9441b75f018b6e99e5e101c5c7669cf0992e

**Comment by tokunbo** [comment]
Actually, the more I think about this the more I wonder if people would really want this to happen. 
What I've done is added a flag to turn on this behavior if you need it.

```
Adding flag --parallel-scenario-feature-hooks

By default, if you run parallel scenarios the
before/after feature in environment.py won't run for
those scenarios. This flag will make them run for each
scenario. NOTE: This means before_feature and
after_feature will run repeatedly and concurrently for
each scenario.
```

**Comment by tokunbo** [comment]
Thinking even more about this.... I may also add a parallel element option called "diamonds". That'll be harder to do so I'm going to think about it for awhile, but if I do add it the functionality would be each feature runs one by one but the scenarios in them run in parallel. Like a chain of diamonds:
![diamond](https://cloud.githubusercontent.com/assets/2522019/18618754/ec9e3db2-7da1-11e6-9aa0-c28718fff103.png)

**Comment by anuragh27crony** [comment]
@tokunbo with your previous fix i was more curious about the sequence of it execution. Since this sequence becomes more important given the nature of code present in after_feature & before_feature hooks. I like the idea of giving different options based on their usage.

Above diamond structure does makes sense when only single execution is expected from before_feature & after_feature hooks with a minor trade off in threads end-up in waiting till these hooks are executed.

**Comment by tokunbo** [comment]
The sequence is to first run the before_feature, then the feature, then the after_feature... but all the features will run at the same time and the before/after features will also all run at the same time for each feature.

**Comment by tokunbo** [comment]
Like this, 
![bafeature](https://cloud.githubusercontent.com/assets/2522019/18685619/b8b92aec-7f2d-11e6-93c5-0e64ace4e899.png)

**Comment by tokunbo** [comment]
I'm going to close this issue for now, since I think the original issue has been handled with the optional "--parallel-scenario-feature-hooks" flag being added. Improvements and/or new options for something else might come up if I can think of a good approach and have some free time to do it.
