### ISSUE TITLE
bump version of behave to 1.2.5

### ISSUE THREAD

**Issue by ndmanvar** [tokunbo/behave-parallel#11]
Hi,

Would it be possible to bump the version of behave being used to 1.2.5 as it introduces some new features?

Thank you in advance.

-Neil

**Comment by tokunbo** [comment]
I'll try!

**Comment by tokunbo** [comment]
Unfortunately I think behave upstream has advanced well beyond my fork. I can't fit my craziness into their code anymore. And to be honest, I suspect a better way to do this would have been to use behave's well documented API to spit up run tasks instead of what I did hacking around in the core.
